source 'https://rubygems.org'

gem 'aws-sdk', '~> 3.0'
gem 'confidante', '~> 0.27'
gem 'git', '~> 1.8'
gem 'mime-types', '~> 3.3'
gem 'rake', '~> 13.0'
gem 'rake_docker', '~> 2.13'
gem 'rake_fly', '~> 2.7'
gem 'rake_terraform', '~> 1.19'
