---
# General
environment: "production" # use full asset pipeline for all deployed environments

parent_role_arn: "%{hiera('bsn_parent_account_admin_role')}"

content_work_directory: "build/content/%{hiera('deployment_identifier')}"
react_app_backend_base_url: "https://reference-backend-bsn-development-plutonium.bsn-development-potassium.bosonprotocol.io"

parent_domain_name: "bosonprotocol.io"
primary_domain_name: "bsn-development-potassium.%{hiera('parent_domain_name')}"
certificate_domain_name: "%{hiera('primary_domain_name')}"

primary_address: "%{hiera('component')}-%{deployment_label}.%{hiera('primary_domain_name')}"
other_addresses:
  - "reference-frontend-preview.%{hiera('parent_domain_name')}"

# State
parent_common_state_bucket_name: "bsn-aws-parent-account-bsn-parent-default"
parent_common_state_key: "common/deployment-state/default.tfstate"
parent_common_state_bucket_region: "%{hiera('region')}"
parent_common_state_bucket_is_encrypted: "true"

common_state_bucket_name: "bsn-aws-application-account-bsn-development-potassium"
common_state_key: "common/deployment-state/default.tfstate"
common_state_bucket_region: "%{hiera('region')}"
common_state_bucket_is_encrypted: "true"

website_state_bucket_name: "%{hiera('storage_bucket_name')}"
website_state_key: "website/deployment-state/default.tfstate"
website_state_bucket_region: "%{hiera('region')}"
website_state_bucket_is_encrypted: "true"
