---
# General
region: "eu-west-2"

component: "reference-frontend"
deployment_identifier: "%{deployment_type}-%{deployment_label}"

source_repository_name: "bosonprotocol/reference-frontend"
source_repository_url: "git@github.com:%{hiera('source_repository_name')}.git"
source_repository_branch: "develop"

storage_bucket_name: "bsn-%{hiera('component')}-%{hiera('deployment_identifier')}"
storage_bucket_encryption: "AES256"

rdm_management_account_id: "031036423983"
