resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

  - name: git-tag
    type: docker-image
    source:
      repository: sarquella/concourse-git-tag-resource

resources:
  - name: source
    type: git-tag
    source:
      uri: ((source_repository_url))
      tag_filter: v*
      private_key: ((git_ssh_key))

  - name: updated-source
    type: git-tag
    source:
      uri: ((source_repository_url))
      tag_filter: v*
      private_key: ((git_ssh_key))

  - name: node-builder-image
    type: docker-image
    source:
      repository: ((node_builder_image_repository_url))
      aws_access_key_id: ((aws_access_key_id))
      aws_secret_access_key: ((aws_secret_access_key))

  - name: notify-success
    type: slack-notification
    source:
      url: ((slack_builds_webhook_url))

  - name: notify-failure
    type: slack-notification
    source:
      url: ((slack_engineering_webhook_url))

groups:
  - name: production-vanadium
    jobs:
      - build
      - test
      - provision-production-vanadium-website
      - provision-production-vanadium-content

jobs:
  - name: build
    serial: true
    plan:
      - in_parallel:
          - get: source
            trigger: true
          - get: node-builder-image
      - task: build
        image: node-builder-image
        file: source/pipelines/shared/build/task.yaml

    on_success: &on_success
      put: notify-success
      params:
        text: ((slack_success_message))
        channel: ((slack_success_channel))

    on_failure: &on_failure
      put: notify-failure
      params:
        text: ((slack_failure_message))
        channel: ((slack_failure_channel))

    on_error: &on_error
      put: notify-failure
      params:
        text: ((slack_error_message))
        channel: ((slack_error_channel))

    on_abort: &on_abort
      put: notify-failure
      params:
        text: ((slack_abort_message))
        channel: ((slack_abort_channel))

  - name: test
    plan:
      - in_parallel:
          - get: source
            trigger: true
            passed:
              - build
          - get: updated-source
          - get: node-builder-image
      - task: test
        image: node-builder-image
        file: source/pipelines/shared/coverage/task.yaml
      - put: updated-source
        params:
          repository: source

    on_success: *on_success
    on_failure: *on_failure
    on_error: *on_error
    on_abort: *on_abort

  - name: provision-production-vanadium-website
    serial: true
    plan:
      - in_parallel:
          - get: source
            trigger: true
            passed:
              - test
          - get: node-builder-image
      - task: provision-website
        image: node-builder-image
        file: source/pipelines/tag/provision-website/task.yaml
        params:
          GPG_KEY: ((gpg_key))
          PROVISIONING_ROLE_ARN: ((production_vanadium_provisioning_role_arn))
          DEPLOYMENT_TYPE: ((production_vanadium_deployment_type))
          DEPLOYMENT_LABEL: ((production_vanadium_deployment_label))

    on_success: *on_success
    on_failure: *on_failure
    on_error: *on_error
    on_abort: *on_abort

  - name: provision-production-vanadium-content
    plan:
      - in_parallel:
          - get: source
            trigger: true
            passed:
              - provision-production-vanadium-website
          - get: node-builder-image
      - task: provision-content
        image: node-builder-image
        file: source/pipelines/tag/provision-content/task.yaml
        params:
          GPG_KEY: ((gpg_key))
          PROVISIONING_ROLE_ARN: ((production_vanadium_provisioning_role_arn))
          DEPLOYMENT_TYPE: ((production_vanadium_deployment_type))
          DEPLOYMENT_LABEL: ((production_vanadium_deployment_label))

    on_success: *on_success
    on_failure: *on_failure
    on_error: *on_error
    on_abort: *on_abort
